apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      app: db
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: quay.io/sina/mysql:8.0
        name: db
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: "BolbolestanDB"
        ports:
        - containerPort: 3306
          name: db
        resources:
          limits:
            cpu: "333m"
            memory: "500M"
          requests:
            cpu: "333m"
            memory: "500M"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          subPath: backend-mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc